### ISSUE TITLE
soda like tabs

### ISSUE THREAD

**Issue by gj1118** [oivva/boxy#41]
can you make tabs like they are there in soda theme (exposed via settings)? i really like those tabs because they are much easier on the eyes unlike the flat tabs ? 

-gagan

**Comment by oivva** [comment]
Please tell me what do you mean? Gradient background and inactive tab styling, right?

**Comment by gj1118** [comment]
Sorry for the late reply. I was thinking of tabs like the following 

![image](https://cloud.githubusercontent.com/assets/473101/15664278/7e704236-26d0-11e6-9e5e-4c610ffc6f12.png)

**Comment by oivva** [comment]
Understood, thanks. Sorry, I think it's hard to add settings like this in the current implementation, because I minimized usage of images. Another reason why I don't want to add soda-like tabs that these themes are flat, we will need to review styles of almost all components for unified soda look.

In your case better to use Soda with you favorite color scheme. Or look at the [tab options](https://github.com/oivva/boxy/wiki/Settings#tabs), maybe you'll find another solution that fits your needs.
