### ISSUE TITLE
The text on tab is cut for when I set "theme_font_md": true.

### ISSUE THREAD

**Issue by sandogeek** [oivva/boxy#45]
![image](https://cloud.githubusercontent.com/assets/16507453/15447776/f19d1ffc-1f7f-11e6-96ae-35c9b388a303.png)
For exsample,the underline is mising in this picture,even if I change my tab size to lg.

**Comment by oivva** [comment]
See https://github.com/oivva/boxy/wiki/Settings#tab-font, this is due to [Sublime Text Issue](https://github.com/SublimeTextIssues/Core/issues/694).

**Comment by oivva** [comment]
Another info from our [wiki](https://github.com/oivva/boxy/wiki/Settings#global):

For example, you want to increase font size of all UI controls via setting a global font size option. But due to this issue you can find that lower half of the tab label is cut off. In such cases just override font size by setting a font size option specific to the tab:

```js
"theme_font_xl": true, // Set global font size to extra large
"theme_tab_font_sm": true, // Fix tab cut off by setting font size to small (11px)
```

**Comment by sandogeek** [comment]
You make a nice theme.Thx.
