### ISSUE TITLE
Troubles with file type icons

### ISSUE THREAD

**Issue by afishr** [oivva/boxy#76]
I just have some troubles with file icons in sidebar, because they differ from your screens.
![34](https://cloud.githubusercontent.com/assets/11911546/16243177/af44d572-37fe-11e6-9742-f7e9033ed8f3.JPG)
![55](https://cloud.githubusercontent.com/assets/11911546/16243178/af47d060-37fe-11e6-9830-dffb08e97295.JPG)
![4](https://cloud.githubusercontent.com/assets/11911546/16243179/af574702-37fe-11e6-98be-5d1e73d79df8.JPG)
What could be the problem? Maybe some additional settings?
P.S. Operating System: Windows 10.
Sublime: Build 3114

**Comment by oivva** [comment]
Ah! Just install syntax files for those languages and restart Sublime Text.

E.g.

[SCSS](https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20Sass)
[LESS](https://packagecontrol.io/packages/LESS)
[Coffee](https://packagecontrol.io/packages/Better%20CoffeeScript)

Due to new Sublime's syntax engine it's not possible to add such custom icons as Gulpfile, Gruntfile & etc. I left them for the future releases.

**Comment by michaelblyons** [comment]
Interesting. Does that mean that the icons are mapped to the root scope?

**Comment by afishr** [comment]
oh, man, thanks! Really, you just saved a lot of my time :) Your theme are really cool :+1:

**Comment by oivva** [comment]
@michaelblyons Yep) More details:

[Sidebar icons in themes](https://forum.sublimetext.com/t/sidebar-icons-in-themes/13119/17)
[Syntax Conflict](https://github.com/lefoy/cyanide-theme/issues/40)
[Extending existing syntaxes](https://forum.sublimetext.com/t/extending-existing-syntax-definitions/19663)
